web:
  mode: debug
  port: 30001
  
db:
  host: 127.0.0.1
  port: 3306
  user: root
  password: "secret123"
  name: "shipping_aggregator"
  debug: true
  
log:
  level: info
  console_enabled: true
  file_path: logs/app.log
  max_size: 10MB
  max_backups: 5
  max_age: 30
  compress: true
  
redis:
  host: 127.0.0.1
  port: 6379
  password: 
  db: 0
  
biteship:
    base_url: "https://api.biteship.com"
    api_key: "biteship_test.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQXpraWEgVGVzdGluZyIsInVzZXJJZCI6IjY4ODczMDc3ZTRhM2RiMDAxMjBlYzcwYSIsImlhdCI6MTc1MzY5MDc5N30.s1QcOe1g9aNkUMx4uN6Q8ZX9CxnVNolU2m6tNKoK-hE"