web:
  mode: debug
  port: 30001
  
db:
  host: 127.0.0.1
  port: 3306
  user: root
  password: "secret123"
  name: "shipping_aggregator"
  debug: true
  
log:
  level: debug
  console_enabled: true
  file_path: logs/app.log
  max_size: 10MB
  max_backups: 5
  max_age: 30
  compress: true
  
redis:
  host: 127.0.0.1
  port: 6379
  password: 
  db: 5
  
biteship:
    base_url: "https://api.biteship.com"
    api_key: "biteship_live.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQXpraWEiLCJ1c2VySWQiOiI2ODg3MzA3N2U0YTNkYjAwMTIwZWM3MGEiLCJpYXQiOjE3NTM5Mjk1MzZ9.4Yxst8-moRyvcO6NNTT2339zc3GBBTYKFNVePmcJLBA"